import type { UMKM, User } from "@/lib/types";

export const mockUsers: User[] = [
  {
    id: "user-1",
    name: "Admin Desa",
    email: "admin@desa.com",
    role: "Admin Desa",
    rtRw: "-",
    avatarUrl: "https://placehold.co/100x100.png",
  },
  {
    id: "user-2",
    name: "Budi Santoso",
    email: "budi.s@desa.com",
    role: "Petugas RT/RW",
    rtRw: "001/001",
    avatarUrl: "https://placehold.co/100x100.png",
  },
  {
    id: "user-3",
    name: "Siti Aminah",
    email: "siti.a@desa.com",
    role: "Petugas RT/RW",
    rtRw: "002/001",
    avatarUrl: "https://placehold.co/100x100.png",
  },
  {
    id: "user-4",
    name: "Agus Wijaya",
    email: "agus.w@desa.com",
    role: "Petugas RT/RW",
    rtRw: "003/002",
    avatarUrl: "https://placehold.co/100x100.png",
  },
];

export const mockUmkm: UMKM[] = [
  {
    id: "umkm-1",
    businessName: "Warung Makan Bu Siti",
    ownerName: "Siti Rahayu",
    nib: "1234567890123",
    businessType: "Kuliner",
    address: "Jl. Merdeka No. 10",
    rtRw: "001/001",
    contact: "081234567890",
    status: "aktif",
    startDate: "2018-05-15",
    employeeCount: 3,
    description: "Menyediakan masakan rumahan khas Sunda.",
    imageUrl: "https://placehold.co/600x400.png",
  },
  {
    id: "umkm-2",
    businessName: "Fashionable Hijab",
    ownerName: "Aisyah Putri",
    nib: "2345678901234",
    businessType: "Fashion",
    address: "Jl. Pahlawan No. 5",
    rtRw: "002/001",
    contact: "082345678901",
    status: "aktif",
    startDate: "2020-01-20",
    employeeCount: 5,
    description: "Butik hijab dengan model terbaru dan bahan berkualitas.",
    imageUrl: "https://placehold.co/600x400.png",
  },
  {
    id: "umkm-3",
    businessName: "Kerajinan Bambu Pakde",
    ownerName: "Joko Susilo",
    nib: "3456789012345",
    businessType: "Kerajinan",
    address: "Gg. Kreatif No. 1",
    rtRw: "001/001",
    contact: "083456789012",
    status: "aktif",
    startDate: "2015-11-10",
    employeeCount: 8,
    description: "Produk kerajinan tangan dari bambu berkualitas ekspor.",
    imageUrl: "https://placehold.co/600x400.png",
  },
  {
    id: "umkm-4",
    businessName: "Bengkel Motor Jaya",
    ownerName: "Ujang Supriadi",
    nib: "4567890123456",
    businessType: "Jasa",
    address: "Jl. Raya Desa No. 25",
    rtRw: "003/002",
    contact: "084567890123",
    status: "aktif",
    startDate: "2019-02-28",
    employeeCount: 2,
    description: "Jasa servis dan perbaikan motor segala merk.",
    imageUrl: "https://placehold.co/600x400.png",
  },
  {
    id: "umkm-5",
    businessName: "Tani Makmur",
    ownerName: "Sumarni",
    nib: "5678901234567",
    businessType: "Pertanian",
    address: "Area Sawah Sejahtera",
    rtRw: "002/001",
    contact: "085678901234",
    status: "tidak aktif",
    startDate: "2017-07-07",
    employeeCount: 10,
    description: "Kelompok tani penghasil beras organik.",
    imageUrl: "https://placehold.co/600x400.png",
  },
    {
    id: "umkm-6",
    businessName: "Sate Ayam Madura Cak Mamat",
    ownerName: "Mamat Alkatiri",
    nib: "6789012345678",
    businessType: "Kuliner",
    address: "Jl. Kuliner No. 12",
    rtRw: "003/002",
    contact: "081234567891",
    status: "aktif",
    startDate: "2021-08-17",
    employeeCount: 4,
    description: "Sate ayam dengan bumbu kacang khas Madura yang legendaris.",
    imageUrl: "https://placehold.co/600x400.png",
  },
];
